# Generated by Django 3.2.7 on 2023-03-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20221003_1304'),
        ('userauths', '0003_alter_profile_saved_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='saved_videos',
            field=models.ManyToManyField(blank=True, related_name='saved_videos', to='core.Video'),
        ),
    ]
