# Generated by Django 3.2.7 on 2023-04-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20221003_1304'),
        ('userauths', '0004_alter_profile_saved_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='downloaded_videos',
            field=models.ManyToManyField(blank=True, related_name='downloaded_videos', to='core.Video'),
        ),
    ]
